sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "7"
  - "8"

cache:
  directories:
    - "node_modules"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - ./node_modules/bower/bin/bower install

script:
  - npm test

git:
  depth: 10
