language: node_js

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
  - "7"
  - "8"

cache:
  directories:
    - "node_modules"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - ./node_modules/bower/bin/bower install
  - ./nodeserver.sh > /dev/null &

script:
  - npm test

sudo: true

git:
  depth: 10
